// templates/themes/headspa.ts
// Headspa Premium Template - Wellness & Spa Landing Page

import type { HeadingConfig, TextConfig, ButtonConfig } from '../../../content.types';
import type { Template } from '../types';

/**
 * Premium Headspa Template
 * Professional wellness & spa landing page
 */
export const headspaTemplate: Template = {
  metadata: {
    id: 'headspa-premium',
    name: 'Premium Headspa',
    category: 'wellness',
    description: 'Professional wellness and spa landing page with modern design',
    author: 'Zeyno',
    tags: ['spa', 'wellness', 'massage', 'headspa', 'relaxation', 'beauty'],
    colors: {
      primary: '#764ba2',
      secondary: '#667eea',
      accent: '#ffffff',
    },
    isPremium: false,
    isPublished: true,
  },
  sections: [
    // ============================================================================
    // HERO SECTION
    // ============================================================================
    {
      section: {
        id: 'hero-section',
        type: 'section',
        width: '100%',
        paddingTop: 120,
        paddingBottom: 120,
        background: {
          type: 'gradient',
          gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        },
        children: [],
      },
      container: {
        id: 'hero-container',
        type: 'container',
        variant: 'standard',
        maxWidth: 1200,
        paddingX: 24,
        margin: 'auto',
        children: [],
      },
      stacks: [
        {
          id: 'hero-main-stack',
          type: 'stack',
          direction: 'horizontal',
          gap: 64,
          align: 'center',
          justify: 'space-between',
          width: 'fill',
          children: [
            {
              id: 'hero-left-stack',
              type: 'stack',
              direction: 'vertical',
              gap: 24,
              align: 'start',
              justify: 'center',
              maxWidth: 600,
              children: [
                {
                  id: 'hero-badge',
                  type: 'text',
                  text: '✨ Yeni Açıldık - İlk 50 Müşteriye %20 İndirim',
                  fontSize: 14,
                  fontWeight: 600,
                  color: '#ffffff',
                  textAlign: 'left',
                  marginBottom: 0,
                } as TextConfig,
                {
                  id: 'hero-title',
                  type: 'heading',
                  text: 'Premium Headspa Deneyimi',
                  level: 'h1',
                  fontSize: 56,
                  fontWeight: 700,
                  color: '#ffffff',
                  textAlign: 'left',
                  lineHeight: 1.2,
                } as HeadingConfig,
                {
                  id: 'hero-subtitle',
                  type: 'text',
                  text: 'Stresinizi atın, zihninizi dinlendirin. Profesyonel terapistlerimizle lüks wellness tedavisi.',
                  fontSize: 20,
                  fontWeight: 400,
                  color: 'rgba(255, 255, 255, 0.9)',
                  textAlign: 'left',
                  lineHeight: 1.6,
                } as TextConfig,
                {
                  id: 'hero-buttons-stack',
                  type: 'stack',
                  direction: 'horizontal',
                  gap: 16,
                  align: 'center',
                  justify: 'start',
                  children: [
                    {
                      id: 'hero-cta-button',
                      type: 'button',
                      text: 'Hemen Randevu Al',
                      variant: 'primary',
                      size: 'lg',
                      backgroundColor: '#ffffff',
                      textColor: '#764ba2',
                      fontSize: 18,
                      fontWeight: 600,
                      paddingX: 32,
                      paddingY: 16,
                      borderRadius: 8,
                      href: '#booking',
                    } as ButtonConfig,
                    {
                      id: 'hero-secondary-button',
                      type: 'button',
                      text: 'Hizmetleri İncele',
                      variant: 'outline',
                      size: 'lg',
                      backgroundColor: 'transparent',
                      textColor: '#ffffff',
                      borderColor: '#ffffff',
                      fontSize: 18,
                      fontWeight: 600,
                      paddingX: 32,
                      paddingY: 16,
                      borderRadius: 8,
                      href: '#services',
                    } as ButtonConfig,
                  ],
                },
              ],
            },
            {
              id: 'hero-image',
              type: 'image',
              src: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=500&h=500&fit=crop&q=80', // ✅ Unsplash spa image
              alt: 'Premium Headspa Treatment',
              width: 500,
              height: 500,
              objectFit: 'cover',
              borderRadius: 16,
            } as any,
          ],
        },
      ],
      grids: [],
    },

    // ============================================================================
    // FEATURES SECTION
    // ============================================================================
    {
      section: {
        id: 'features-section',
        type: 'section',
        width: '100%',
        paddingTop: 80,
        paddingBottom: 80,
        background: {
          type: 'color',
          color: '#f9fafb',
        },
        children: [],
      },
      container: {
        id: 'features-container',
        type: 'container',
        variant: 'standard',
        maxWidth: 1200,
        paddingX: 24,
        margin: 'auto',
        children: [],
      },
      stacks: [
        {
          id: 'features-header-stack',
          type: 'stack',
          direction: 'vertical',
          gap: 16,
          align: 'center',
          justify: 'center',
          width: 'fill',
          children: [
            {
              id: 'features-title',
              type: 'heading',
              text: 'Neden Bizi Seçmelisiniz?',
              level: 'h2',
              fontSize: 42,
              fontWeight: 700,
              color: '#1f2937',
              textAlign: 'center',
              marginBottom: 8,
            } as HeadingConfig,
            {
              id: 'features-subtitle',
              type: 'text',
              text: 'Size özel wellness deneyimi için profesyonel ekibimiz ve premium hizmetlerimiz',
              fontSize: 18,
              fontWeight: 400,
              color: '#6b7280',
              textAlign: 'center',
              maxWidth: 700,
              marginBottom: 48,
            } as TextConfig,
          ],
        },
      ],
      grids: [
        {
          id: 'features-grid',
          type: 'grid',
          columns: 3,
          gap: 32,
          align: 'start',
          padding: 0,
          children: [
            {
              id: 'feature-card-1',
              type: 'text',
              text: '🧘‍♀️',
              fontSize: 48,
              fontWeight: 400,
              color: '#764ba2',
              textAlign: 'center',
              marginBottom: 16,
            } as TextConfig,
            {
              id: 'feature-1-title',
              type: 'heading',
              text: 'Profesyonel Ekip',
              level: 'h3',
              fontSize: 24,
              fontWeight: 600,
              color: '#1f2937',
              textAlign: 'center',
              marginBottom: 8,
            } as HeadingConfig,
            {
              id: 'feature-1-desc',
              type: 'text',
              text: 'Sertifikalı terapistlerimiz, yıllarca deneyimle size hizmet ediyor',
              fontSize: 16,
              fontWeight: 400,
              color: '#6b7280',
              textAlign: 'center',
            } as TextConfig,
            {
              id: 'feature-card-2',
              type: 'text',
              text: '✨',
              fontSize: 48,
              fontWeight: 400,
              color: '#764ba2',
              textAlign: 'center',
              marginBottom: 16,
            } as TextConfig,
            {
              id: 'feature-2-title',
              type: 'heading',
              text: 'Premium Ürünler',
              level: 'h3',
              fontSize: 24,
              fontWeight: 600,
              color: '#1f2937',
              textAlign: 'center',
              marginBottom: 8,
            } as HeadingConfig,
            {
              id: 'feature-2-desc',
              type: 'text',
              text: 'Doğal ve organik malzemeler kullanarak cildinize özen gösteriyoruz',
              fontSize: 16,
              fontWeight: 400,
              color: '#6b7280',
              textAlign: 'center',
            } as TextConfig,
            {
              id: 'feature-card-3',
              type: 'text',
              text: '🎯',
              fontSize: 48,
              fontWeight: 400,
              color: '#764ba2',
              textAlign: 'center',
              marginBottom: 16,
            } as TextConfig,
            {
              id: 'feature-3-title',
              type: 'heading',
              text: 'Kişiselleştirilmiş',
              level: 'h3',
              fontSize: 24,
              fontWeight: 600,
              color: '#1f2937',
              textAlign: 'center',
              marginBottom: 8,
            } as HeadingConfig,
            {
              id: 'feature-3-desc',
              type: 'text',
              text: 'İhtiyaçlarınıza özel tedavi planı ile maksimum rahatlama',
              fontSize: 16,
              fontWeight: 400,
              color: '#6b7280',
              textAlign: 'center',
            } as TextConfig,
          ],
        },
      ],
    },

    // ============================================================================
    // SERVICES SECTION
    // ============================================================================
    {
      section: {
        id: 'services-section',
        type: 'section',
        width: '100%',
        paddingTop: 80,
        paddingBottom: 80,
        background: {
          type: 'color',
          color: '#ffffff',
        },
        children: [],
      },
      container: {
        id: 'services-container',
        type: 'container',
        variant: 'standard',
        maxWidth: 1200,
        paddingX: 24,
        margin: 'auto',
        children: [],
      },
      stacks: [
        {
          id: 'services-header',
          type: 'stack',
          direction: 'vertical',
          gap: 16,
          align: 'center',
          children: [
            {
              id: 'services-title',
              type: 'heading',
              text: 'Popüler Hizmetlerimiz',
              level: 'h2',
              fontSize: 42,
              fontWeight: 700,
              color: '#1f2937',
              textAlign: 'center',
              marginBottom: 48,
            } as HeadingConfig,
          ],
        },
        {
          id: 'services-cards-stack',
          type: 'stack',
          direction: 'horizontal',
          gap: 32,
          align: 'stretch',
          justify: 'space-between',
          children: [
            {
              id: 'service-card-1',
              type: 'stack',
              direction: 'vertical',
              gap: 16,
              align: 'start',
              padding: 32,
              background: {
                type: 'color',
                color: '#f9fafb',
              },
              border: {
                enabled: true,
                width: 1,
                style: 'solid',
                color: '#e5e7eb',
                radius: 12,
              },
              children: [
                {
                  id: 'service-1-title',
                  type: 'heading',
                  text: 'Classic Headspa',
                  level: 'h3',
                  fontSize: 28,
                  fontWeight: 600,
                  color: '#1f2937',
                  textAlign: 'left',
                } as HeadingConfig,
                {
                  id: 'service-1-desc',
                  type: 'text',
                  text: 'Rahatlatıcı kafa masajı ve aromaterapi ile stres atma seansı. Günlük yorgunluğu atın.',
                  fontSize: 16,
                  fontWeight: 400,
                  color: '#6b7280',
                  textAlign: 'left',
                  lineHeight: 1.6,
                } as TextConfig,
                {
                  id: 'service-1-features',
                  type: 'text',
                  text: '• Kafa masajı\n• Aromaterapi\n• Rahatlama müziği',
                  fontSize: 14,
                  fontWeight: 400,
                  color: '#9ca3af',
                  textAlign: 'left',
                  lineHeight: 1.8,
                } as TextConfig,
                {
                  id: 'service-1-price',
                  type: 'text',
                  text: '₺85',
                  fontSize: 32,
                  fontWeight: 700,
                  color: '#764ba2',
                  textAlign: 'left',
                  marginTop: 16,
                } as TextConfig,
                {
                  id: 'service-1-duration',
                  type: 'text',
                  text: '60 dakika',
                  fontSize: 14,
                  fontWeight: 400,
                  color: '#6b7280',
                  textAlign: 'left',
                } as TextConfig,
                {
                  id: 'service-1-button',
                  type: 'button',
                  text: 'Randevu Al',
                  variant: 'primary',
                  size: 'md',
                  backgroundColor: '#764ba2',
                  textColor: '#ffffff',
                  fontSize: 16,
                  fontWeight: 600,
                  paddingX: 24,
                  paddingY: 12,
                  borderRadius: 8,
                } as ButtonConfig,
              ],
            },
            {
              id: 'service-card-2',
              type: 'stack',
              direction: 'vertical',
              gap: 16,
              align: 'start',
              padding: 32,
              background: {
                type: 'gradient',
                gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
              },
              border: {
                enabled: false,
                width: 0,
                style: 'solid',
                color: '#000000',
                radius: 12,
              },
              shadow: {
                enabled: true,
                offsetX: 0,
                offsetY: 8,
                blur: 24,
                spread: 0,
                color: 'rgba(118, 75, 162, 0.3)',
              },
              children: [
                {
                  id: 'service-2-badge',
                  type: 'text',
                  text: '⭐ EN POPÜLER',
                  fontSize: 12,
                  fontWeight: 700,
                  color: '#ffffff',
                  textAlign: 'left',
                  marginBottom: 8,
                } as TextConfig,
                {
                  id: 'service-2-title',
                  type: 'heading',
                  text: 'Premium Headspa',
                  level: 'h3',
                  fontSize: 28,
                  fontWeight: 600,
                  color: '#ffffff',
                  textAlign: 'left',
                } as HeadingConfig,
                {
                  id: 'service-2-desc',
                  type: 'text',
                  text: 'Lüks wellness deneyimi: Headspa + Yüz masajı + Aromaterapi. Kendinize değer verin.',
                  fontSize: 16,
                  fontWeight: 400,
                  color: 'rgba(255,255,255,0.9)',
                  textAlign: 'left',
                  lineHeight: 1.6,
                } as TextConfig,
                {
                  id: 'service-2-features',
                  type: 'text',
                  text: '• Premium kafa masajı\n• Yüz masajı\n• Aromaterapi\n• Sıcak havlu uygulaması',
                  fontSize: 14,
                  fontWeight: 400,
                  color: 'rgba(255,255,255,0.8)',
                  textAlign: 'left',
                  lineHeight: 1.8,
                } as TextConfig,
                {
                  id: 'service-2-price',
                  type: 'text',
                  text: '₺150',
                  fontSize: 32,
                  fontWeight: 700,
                  color: '#ffffff',
                  textAlign: 'left',
                  marginTop: 16,
                } as TextConfig,
                {
                  id: 'service-2-duration',
                  type: 'text',
                  text: '90 dakika',
                  fontSize: 14,
                  fontWeight: 400,
                  color: 'rgba(255,255,255,0.8)',
                  textAlign: 'left',
                } as TextConfig,
                {
                  id: 'service-2-button',
                  type: 'button',
                  text: 'Hemen Rezerve Et',
                  variant: 'primary',
                  size: 'md',
                  backgroundColor: '#ffffff',
                  textColor: '#764ba2',
                  fontSize: 16,
                  fontWeight: 600,
                  paddingX: 24,
                  paddingY: 12,
                  borderRadius: 8,
                } as ButtonConfig,
              ],
            },
          ],
        },
      ],
      grids: [],
    },

    // ============================================================================
    // CTA SECTION
    // ============================================================================
    {
      section: {
        id: 'cta-section',
        type: 'section',
        width: '100%',
        paddingTop: 80,
        paddingBottom: 80,
        background: {
          type: 'color',
          color: '#1f2937',
        },
        children: [],
      },
      container: {
        id: 'cta-container',
        type: 'container',
        variant: 'narrow',
        maxWidth: 940,
        paddingX: 24,
        margin: 'auto',
        children: [],
      },
      stacks: [
        {
          id: 'cta-stack',
          type: 'stack',
          direction: 'vertical',
          gap: 24,
          align: 'center',
          justify: 'center',
          children: [
            {
              id: 'cta-title',
              type: 'heading',
              text: 'Hazır mısınız?',
              level: 'h2',
              fontSize: 42,
              fontWeight: 700,
              color: '#ffffff',
              textAlign: 'center',
            } as HeadingConfig,
            {
              id: 'cta-text',
              type: 'text',
              text: 'İlk randevunuzu bugün alın ve kendinize özel wellness deneyimini yaşayın',
              fontSize: 18,
              fontWeight: 400,
              color: 'rgba(255,255,255,0.8)',
              textAlign: 'center',
              maxWidth: 600,
              lineHeight: 1.6,
            } as TextConfig,
            {
              id: 'cta-button',
              type: 'button',
              text: 'Şimdi Randevu Al',
              variant: 'primary',
              size: 'lg',
              backgroundColor: '#764ba2',
              textColor: '#ffffff',
              fontSize: 20,
              fontWeight: 600,
              paddingX: 40,
              paddingY: 16,
              borderRadius: 8,
            } as ButtonConfig,
          ],
        },
      ],
      grids: [],
    },
  ],
};